/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package descontinuados;

import Util.DocumentSizeFilter;
import Componentes.Componentes;
import Controlador.CarregaEndereco;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Maycon
 */
public class CadastroDePais extends javax.swing.JFrame {
    JButton gravar;
    JButton remover;
    JButton pesquisar;
    JButton cancelar;
    
    Componentes c = new Componentes();
    CarregaEndereco carregaEndereco = new CarregaEndereco();
    /**
     * Creates new form CadastroDePais
     */
    public CadastroDePais() {
        initComponents();
        ((AbstractDocument) ((JTextField) jcbSiglaPais.getEditor().getEditorComponent()).getDocument())
                .setDocumentFilter(new DocumentSizeFilter(2));
        
        gravar = c.criaBotaoGravar();
//        pesquisar = c.criaBotaoPesquisar();
//        remover = c.criaBotaoRemover();
//        cancelar = c.criaBotaoCancelar();
        
        gravar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarActionPerformed(evt);
            }
            private void gravarActionPerformed(ActionEvent evt) {
                
            }
        });
        
        jcbNomePais.setModel(carregaEndereco.carregaPais());
        
        jpnControles.add(gravar);
        jpnControles.add(pesquisar);
        jpnControles.add(remover);
        jpnControles.add(cancelar);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jpCamponentes = new javax.swing.JPanel();
        jpLabelPais = new javax.swing.JPanel();
        lbNomePais = new javax.swing.JLabel();
        lbSigla = new javax.swing.JLabel();
        lbCodigoPais = new javax.swing.JLabel();
        jpEditoresPais = new javax.swing.JPanel();
        jcbNomePais = new javax.swing.JComboBox();
        jpnCampoSigla = new javax.swing.JPanel();
        jcbSiglaPais = new javax.swing.JComboBox();
        jtfCodigoEstado = new javax.swing.JTextField();
        jpnIDReferencia = new javax.swing.JPanel();
        lbIDReferencia = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jpnControles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro De País", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jpCamponentes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jpLabelPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpLabelPais.setMinimumSize(new java.awt.Dimension(52, 70));
        jpLabelPais.setPreferredSize(new java.awt.Dimension(52, 70));
        jpLabelPais.setLayout(new java.awt.GridLayout(3, 0));

        lbNomePais.setText("Nome:");
        jpLabelPais.add(lbNomePais);

        lbSigla.setText("Sigla:");
        lbSigla.setMaximumSize(new java.awt.Dimension(31, 14));
        lbSigla.setMinimumSize(new java.awt.Dimension(31, 14));
        lbSigla.setPreferredSize(new java.awt.Dimension(31, 14));
        jpLabelPais.add(lbSigla);

        lbCodigoPais.setText("Código:");
        jpLabelPais.add(lbCodigoPais);

        jpEditoresPais.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jcbNomePais.setEditable(true);
        jpEditoresPais.add(jcbNomePais);

        jcbSiglaPais.setEditable(true);
        jcbSiglaPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BR", "PT" }));

        javax.swing.GroupLayout jpnCampoSiglaLayout = new javax.swing.GroupLayout(jpnCampoSigla);
        jpnCampoSigla.setLayout(jpnCampoSiglaLayout);
        jpnCampoSiglaLayout.setHorizontalGroup(
            jpnCampoSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCampoSiglaLayout.createSequentialGroup()
                .addComponent(jcbSiglaPais, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 216, Short.MAX_VALUE))
        );
        jpnCampoSiglaLayout.setVerticalGroup(
            jpnCampoSiglaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCampoSiglaLayout.createSequentialGroup()
                .addComponent(jcbSiglaPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpEditoresPais.add(jpnCampoSigla);
        jpEditoresPais.add(jtfCodigoEstado);

        lbIDReferencia.setText("ID de Referência:");

        lbID.setText("(nenhum item selecionado)");
        lbID.setEnabled(false);

        javax.swing.GroupLayout jpnIDReferenciaLayout = new javax.swing.GroupLayout(jpnIDReferencia);
        jpnIDReferencia.setLayout(jpnIDReferenciaLayout);
        jpnIDReferenciaLayout.setHorizontalGroup(
            jpnIDReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIDReferenciaLayout.createSequentialGroup()
                .addComponent(lbIDReferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbID)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnIDReferenciaLayout.setVerticalGroup(
            jpnIDReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnIDReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbIDReferencia)
                .addComponent(lbID))
        );

        javax.swing.GroupLayout jpCamponentesLayout = new javax.swing.GroupLayout(jpCamponentes);
        jpCamponentes.setLayout(jpCamponentesLayout);
        jpCamponentesLayout.setHorizontalGroup(
            jpCamponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamponentesLayout.createSequentialGroup()
                .addGroup(jpCamponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamponentesLayout.createSequentialGroup()
                        .addComponent(jpLabelPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpEditoresPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnIDReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpCamponentesLayout.setVerticalGroup(
            jpCamponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamponentesLayout.createSequentialGroup()
                .addGroup(jpCamponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLabelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEditoresPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnIDReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnControles.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCamponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpCamponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnControles, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDePais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDePais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDePais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDePais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroDePais().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcbNomePais;
    private javax.swing.JComboBox jcbSiglaPais;
    private javax.swing.JPanel jpCamponentes;
    private javax.swing.JPanel jpEditoresPais;
    private javax.swing.JPanel jpLabelPais;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpnCampoSigla;
    private javax.swing.JPanel jpnControles;
    private javax.swing.JPanel jpnIDReferencia;
    private javax.swing.JTextField jtfCodigoEstado;
    private javax.swing.JLabel lbCodigoPais;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbIDReferencia;
    private javax.swing.JLabel lbNomePais;
    private javax.swing.JLabel lbSigla;
    // End of variables declaration//GEN-END:variables
}
