/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Venda;

import Componentes.Componentes;
import controller.Cadastro.CaixaController;
import controller.Cadastro.Administrativo.UsuarioController;
import controller.Cadastro.VendaAberturaFechamentoCaixaController;
import controller.Mensagens;
import javax.swing.JButton;
import modelo.AberturaCaixa;
import modelo.Caixa;
import modelo.Session;
import modelo.Usuario;

/**
 *
 * @author Bruno
 */
public class VendaAberturaFechamentoCaixa extends javax.swing.JDialog {

    /**
     * Creates new form VendaAberturaFechamentoCaixa
     */
    VendaAberturaFechamentoCaixaController vendaAberturaFechamentoCaixaController;
    CaixaController caixaController;
    UsuarioController usuarioController;
    Caixa caixa;
    AberturaCaixa aberturaCaixa;
    Usuario usuario;
    Componentes c = new Componentes();
    Mensagens m;
    JButton jbGravar = c.criaBotaoGravar();
    JButton jbExcluir = c.criaBotaoExcluir();

    public VendaAberturaFechamentoCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        caixaController = new CaixaController();
        usuarioController = new UsuarioController();

        jlUsuarioPerfil.setText(" ");
        jlUsuarioResp.setText(" ");
        jlUsuarioRespAbertura.setText(" ");

        jbGravar = c.criaBotaoGravar();
        jbExcluir = c.criaBotaoExcluir();
        
        jpControles.add(jbGravar);
        jpControles.add(jbExcluir);

        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jcbCaixa.setModel(caixaController.listCaixa());
        jcbUsuarioAbertura.setModel(usuarioController.listUsuarios());

        if (jcbCaixa.getSelectedItem() != null) {
            caixa = (Caixa) jcbCaixa.getSelectedItem();
            jlUsuarioResp.setText(caixa.getUsuarioRespId().getUsuarioName());
            jlUsuarioPerfil.setText(caixa.getUsuarioRespId().getUsuarioPerfil().getPerfilDesc());
            jlUsuarioRespAbertura.setText(caixa.getUsuarioRespId().getUsuarioName());
        }

    }

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {
        acaoGravar();
    }

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {
//        m = new Mensagens();
//        if (p != null) {
//            if (p.getPaisID() != 0) {
//                if (m.jopDeletar("Deseja realmente excluir este Pais ?") == JOptionPane.YES_OPTION) {
////                    acaoRemover();
//                }
//            } else {
//                m.jopAlerta("Para excluir registro, é nescessário efetuar uma busca.");
//            }
//        } else {
//            m.jopAlerta("Para excluir registro, é nescessário efetuar uma busca.");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbUsuario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jcbCaixa = new javax.swing.JComboBox();
        jlUsuarioResp = new javax.swing.JLabel();
        jlUsuarioPerfil = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jrbUserResp = new javax.swing.JRadioButton();
        jrbUserOutro = new javax.swing.JRadioButton();
        jcbUsuarioAbertura = new javax.swing.JComboBox();
        jlUsuarioRespAbertura = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfSaldoInicial = new javax.swing.JTextField();
        jpControles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abertura / Fechamento de Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Caixa:");

        jLabel2.setText("Responsável:");

        jLabel3.setText("Perfil:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcbCaixa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCaixaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUsuarioResp)
                            .addComponent(jlUsuarioPerfil))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jcbCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlUsuarioResp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUsuarioPerfil)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário para abertura do caixa"));

        jbUsuario.add(jrbUserResp);
        jrbUserResp.setSelected(true);
        jrbUserResp.setText("Responsável pelo caixa");
        jrbUserResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUserRespActionPerformed(evt);
            }
        });

        jbUsuario.add(jrbUserOutro);
        jrbUserOutro.setText("Outro usuário");
        jrbUserOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUserOutroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbUserResp)
                    .addComponent(jrbUserOutro))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbUserResp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbUserOutro)
                .addContainerGap())
        );

        jcbUsuarioAbertura.setEnabled(false);
        jcbUsuarioAbertura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbUsuarioAberturaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbUsuarioAbertura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlUsuarioRespAbertura)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jlUsuarioRespAbertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbUsuarioAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Saldo inicial:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpControles.setLayout(new java.awt.GridLayout(1, 0, 2, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpControles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-365)/2, 416, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbUserOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUserOutroActionPerformed
        if (!jcbUsuarioAbertura.isEnabled()) {
            jcbUsuarioAbertura.setEnabled(true);
        }
    }//GEN-LAST:event_jrbUserOutroActionPerformed

    private void jrbUserRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUserRespActionPerformed
        if (jcbCaixa.getSelectedItem() != null) {
            caixa = (Caixa) jcbCaixa.getSelectedItem();
            jlUsuarioRespAbertura.setText(caixa.getUsuarioRespId().getUsuarioName());
            jcbUsuarioAbertura.setEnabled(false);
        }
    }//GEN-LAST:event_jrbUserRespActionPerformed

    private void jcbCaixaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCaixaItemStateChanged
        caixa = (Caixa) jcbCaixa.getSelectedItem();
        jlUsuarioResp.setText(caixa.getUsuarioRespId().getUsuarioName());
        jlUsuarioPerfil.setText(caixa.getUsuarioRespId().getUsuarioPerfil().getPerfilDesc());
        jlUsuarioRespAbertura.setText(caixa.getUsuarioRespId().getUsuarioName());
    }//GEN-LAST:event_jcbCaixaItemStateChanged

    private void jcbUsuarioAberturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbUsuarioAberturaItemStateChanged
        caixa = (Caixa) jcbCaixa.getSelectedItem();
        jlUsuarioRespAbertura.setText(caixa.getUsuarioRespId().getUsuarioName());
    }//GEN-LAST:event_jcbUsuarioAberturaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaAberturaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaAberturaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaAberturaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaAberturaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaAberturaFechamentoCaixa dialog = new VendaAberturaFechamentoCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.ButtonGroup jbUsuario;
    private javax.swing.JComboBox jcbCaixa;
    private javax.swing.JComboBox jcbUsuarioAbertura;
    private javax.swing.JLabel jlUsuarioPerfil;
    private javax.swing.JLabel jlUsuarioResp;
    private javax.swing.JLabel jlUsuarioRespAbertura;
    private javax.swing.JPanel jpControles;
    private javax.swing.JRadioButton jrbUserOutro;
    private javax.swing.JRadioButton jrbUserResp;
    private javax.swing.JTextField jtfSaldoInicial;
    // End of variables declaration//GEN-END:variables

    private void acaoGravar() {
        String avisos = "";
        caixa = (Caixa) jcbCaixa.getSelectedItem();

        caixaController = new CaixaController();
        usuarioController = new UsuarioController();
        vendaAberturaFechamentoCaixaController = new VendaAberturaFechamentoCaixaController();

        if (caixa.getCaixaId() == null) {
            avisos = avisos + "\n Caixa não pode ser vazio";
        }

        if (jrbUserOutro.isSelected()) {
            usuario = (Usuario) jcbUsuarioAbertura.getSelectedItem();
        } else {
            if (avisos.equals("")) {
                caixa = (Caixa) jcbCaixa.getSelectedItem();
                usuario = caixa.getUsuarioRespId();
            }
        }

        if (usuario.getUsuarioId() == null) {
            avisos = avisos + "\n Usuario não pode ser vazio ";
        }

        if (jtfSaldoInicial.getText().equals("")) {
            avisos = avisos + "\n Saldo inicial não pode ser vazio ";
        }


        if (avisos.equals("")) {
            aberturaCaixa = new AberturaCaixa();

            aberturaCaixa.setCaixaId(caixa);
            aberturaCaixa.setUsuarioId(usuario);
            aberturaCaixa.setSaldoInicio(Float.parseFloat(jtfSaldoInicial.getText()));

            aberturaCaixa = vendaAberturaFechamentoCaixaController.gravar(aberturaCaixa);

            if (aberturaCaixa.getAberturaCaixaId() != null) {
                m = new Mensagens();
                m.jopAviso("Caixa " + aberturaCaixa.getCaixaId().getCaixaDesc() + " aberto com sucesso para: \n " + aberturaCaixa.getUsuarioId().getUsuarioName() + "!");
            }
        } else {
            m = new Mensagens();
            m.jopAlerta("Verifique: " + avisos + "!");
            jcbCaixa.requestFocus();
        }
    }
}
