/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Componentes.Componentes;
import Controlador.CarregaEndereco;
import Controlador.ControladorPessoa;
import Controlador.Mensagens;
import Modelo.*;
import Util.VerificaNumeros;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Bruno
 */
public class CadastroPessoal extends javax.swing.JDialog {

    SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
    Mensagens m;
    Componentes c = new Componentes();
    JButton botaoGravar;
    JButton botaoExcluir;
    JButton botaoBuscar;
    CarregaEndereco carregaEndereco = new CarregaEndereco();
    ControladorPessoa controladorPessoa;
    Pessoa p = new Pessoa();
    Telefone t = new Telefone();

    /**
     * Creates new form CadastroPessoal
     */
    public CadastroPessoal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        botaoGravar = c.criaBotaoGravar();
        botaoExcluir = c.criaBotaoExcluir();
        botaoBuscar = c.criaBotaoBuscar();


        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jtfBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                acaoBuscar();
            }
        });

        jpControles.add(botaoGravar);
        jpControles.add(botaoExcluir);
        jpControles.add(botaoBuscar);

        jcbPais.setModel(carregaEndereco.carregaPais());
        jcbPais.setSelectedIndex(0);

        jcbEstado.setModel(carregaEndereco.carregaEstado((Pais) jcbPais.getSelectedItem()));
        jcbEstado.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpAbas = new javax.swing.JTabbedPane();
        jpPessoal = new javax.swing.JPanel();
        jspPainelRolagem = new javax.swing.JScrollPane();
        jpAgrupador = new javax.swing.JPanel();
        jpCadastro = new javax.swing.JPanel();
        jtfBuscar = new javax.swing.JTextField();
        jlBuscar = new javax.swing.JLabel();
        jlCadastro = new javax.swing.JLabel();
        jlCadastroNmr = new javax.swing.JLabel();
        jpDadosPrincipais = new javax.swing.JPanel();
        jpLabelsDP = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jlRG = new javax.swing.JLabel();
        jlCPF_CNPJ = new javax.swing.JLabel();
        jpTextFieldsDP = new javax.swing.JPanel();
        jtfNome = new javax.swing.JTextField();
        jtfRG = new javax.swing.JTextField();
        jtfCPF_CNPJ = new javax.swing.JTextField();
        jftfNome = new javax.swing.JFormattedTextField();
        jpEndereco = new javax.swing.JPanel();
        jpLabelsE = new javax.swing.JPanel();
        jlPais = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlLogradouro = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jlCEP_ZIP = new javax.swing.JLabel();
        jlComplemento = new javax.swing.JLabel();
        jpTextFieldsE = new javax.swing.JPanel();
        jcbPais = new javax.swing.JComboBox();
        jcbEstado = new javax.swing.JComboBox();
        jcbCidade = new javax.swing.JComboBox();
        jcbBairro = new javax.swing.JComboBox();
        jcbLogradouro = new javax.swing.JComboBox();
        jtfNumero = new javax.swing.JTextField();
        jcbCEP_ZIP = new javax.swing.JComboBox();
        jtfComplemento = new javax.swing.JTextField();
        jpDadosPessoais = new javax.swing.JPanel();
        jpLablesDPessoais = new javax.swing.JPanel();
        jlTelefone = new javax.swing.JLabel();
        jlDataNascimento = new javax.swing.JLabel();
        jpTextFieldsDPessoais = new javax.swing.JPanel();
        jftfDataNascimento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfDDD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jpControles = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jpDadosFuncionario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas");

        jtpAbas.setPreferredSize(new java.awt.Dimension(400, 600));

        jspPainelRolagem.setBorder(null);

        jlBuscar.setText("Buscar:");

        jlCadastro.setText("Cadastro:");

        javax.swing.GroupLayout jpCadastroLayout = new javax.swing.GroupLayout(jpCadastro);
        jpCadastro.setLayout(jpCadastroLayout);
        jpCadastroLayout.setHorizontalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCadastroNmr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCadastroLayout.setVerticalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBuscar)
                    .addComponent(jlCadastro)
                    .addComponent(jlCadastroNmr))
                .addContainerGap())
        );

        jpDadosPrincipais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Principais"));

        jpLabelsDP.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jlNome.setText("Nome:");
        jpLabelsDP.add(jlNome);

        jlRG.setText("RG:");
        jpLabelsDP.add(jlRG);

        jlCPF_CNPJ.setText("CPF/CNPJ:");
        jpLabelsDP.add(jlCPF_CNPJ);

        jpTextFieldsDP.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });
        jpTextFieldsDP.add(jtfNome);
        jpTextFieldsDP.add(jtfRG);
        jpTextFieldsDP.add(jtfCPF_CNPJ);

        jftfNome.setText("jFormattedTextField1");
        jpTextFieldsDP.add(jftfNome);

        javax.swing.GroupLayout jpDadosPrincipaisLayout = new javax.swing.GroupLayout(jpDadosPrincipais);
        jpDadosPrincipais.setLayout(jpDadosPrincipaisLayout);
        jpDadosPrincipaisLayout.setHorizontalGroup(
            jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPrincipaisLayout.createSequentialGroup()
                .addComponent(jpLabelsDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTextFieldsDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosPrincipaisLayout.setVerticalGroup(
            jpDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLabelsDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTextFieldsDP, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
        );

        jpEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jpLabelsE.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        jlPais.setText("País:");
        jpLabelsE.add(jlPais);

        jlEstado.setText("Estado:");
        jpLabelsE.add(jlEstado);

        jlCidade.setText("Cidade:");
        jpLabelsE.add(jlCidade);

        jLabel1.setText("Bairro:");
        jpLabelsE.add(jLabel1);

        jlLogradouro.setText("Logradouro:");
        jpLabelsE.add(jlLogradouro);

        jlNumero.setText("Número:");
        jpLabelsE.add(jlNumero);

        jlCEP_ZIP.setText("CEP/ZIP:");
        jpLabelsE.add(jlCEP_ZIP);

        jlComplemento.setText("Complemento:");
        jpLabelsE.add(jlComplemento);

        jpTextFieldsE.setLayout(new java.awt.GridLayout(8, 1, 0, 5));

        jcbPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbPaisItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbPais);

        jcbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEstadoItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbEstado);

        jcbCidade.setEnabled(false);
        jcbCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCidadeItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbCidade);

        jcbBairro.setEnabled(false);
        jcbBairro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBairroItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbBairro);

        jcbLogradouro.setEnabled(false);
        jcbLogradouro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLogradouroItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbLogradouro);
        jpTextFieldsE.add(jtfNumero);

        jcbCEP_ZIP.setEnabled(false);
        jcbCEP_ZIP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCEP_ZIPItemStateChanged(evt);
            }
        });
        jpTextFieldsE.add(jcbCEP_ZIP);
        jpTextFieldsE.add(jtfComplemento);

        javax.swing.GroupLayout jpEnderecoLayout = new javax.swing.GroupLayout(jpEndereco);
        jpEndereco.setLayout(jpEnderecoLayout);
        jpEnderecoLayout.setHorizontalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addComponent(jpLabelsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTextFieldsE, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
        );
        jpEnderecoLayout.setVerticalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLabelsE, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(jpTextFieldsE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jpDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jpLablesDPessoais.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jlTelefone.setText("Telefone:");
        jlTelefone.setEnabled(false);
        jpLablesDPessoais.add(jlTelefone);

        jlDataNascimento.setText("Data de Nascimento:");
        jpLablesDPessoais.add(jlDataNascimento);

        jpTextFieldsDPessoais.setLayout(new java.awt.GridLayout(1, 1, 0, 5));

        jftfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jpTextFieldsDPessoais.add(jftfDataNascimento);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        jLabel3.setText("DDD:");
        jLabel3.setEnabled(false);
        jPanel1.add(jLabel3);

        jtfDDD.setEnabled(false);
        jPanel1.add(jtfDDD);

        jLabel2.setText("Número:");
        jLabel2.setEnabled(false);
        jPanel1.add(jLabel2);

        jtfTelefone.setEnabled(false);
        jPanel1.add(jtfTelefone);

        javax.swing.GroupLayout jpDadosPessoaisLayout = new javax.swing.GroupLayout(jpDadosPessoais);
        jpDadosPessoais.setLayout(jpDadosPessoaisLayout);
        jpDadosPessoaisLayout.setHorizontalGroup(
            jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                .addComponent(jpLablesDPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTextFieldsDPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpDadosPessoaisLayout.setVerticalGroup(
            jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLablesDPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpTextFieldsDPessoais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAgrupadorLayout = new javax.swing.GroupLayout(jpAgrupador);
        jpAgrupador.setLayout(jpAgrupadorLayout);
        jpAgrupadorLayout.setHorizontalGroup(
            jpAgrupadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgrupadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgrupadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosPrincipais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpAgrupadorLayout.setVerticalGroup(
            jpAgrupadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgrupadorLayout.createSequentialGroup()
                .addComponent(jpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDadosPrincipais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jspPainelRolagem.setViewportView(jpAgrupador);

        jpControles.setLayout(new javax.swing.BoxLayout(jpControles, javax.swing.BoxLayout.LINE_AXIS));
        jpControles.add(filler1);
        jpControles.add(filler2);
        jpControles.add(filler3);
        jpControles.add(filler4);
        jpControles.add(filler5);

        javax.swing.GroupLayout jpPessoalLayout = new javax.swing.GroupLayout(jpPessoal);
        jpPessoal.setLayout(jpPessoalLayout);
        jpPessoalLayout.setHorizontalGroup(
            jpPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspPainelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
            .addGroup(jpPessoalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpPessoalLayout.setVerticalGroup(
            jpPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPessoalLayout.createSequentialGroup()
                .addComponent(jspPainelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpAbas.addTab("Dados da Pessoa", jpPessoal);

        javax.swing.GroupLayout jpDadosFuncionarioLayout = new javax.swing.GroupLayout(jpDadosFuncionario);
        jpDadosFuncionario.setLayout(jpDadosFuncionarioLayout);
        jpDadosFuncionarioLayout.setHorizontalGroup(
            jpDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        jpDadosFuncionarioLayout.setVerticalGroup(
            jpDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jtpAbas.addTab("Dados do Funcionário", jpDadosFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        jtpAbas.getAccessibleContext().setAccessibleName("Dados Principais");
        jtpAbas.getAccessibleContext().setAccessibleDescription("Dados Principais");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-715)/2, (screenSize.height-574)/2, 715, 574);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbPaisItemStateChanged
    }//GEN-LAST:event_jcbPaisItemStateChanged

    private void jcbCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCidadeItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            jcbBairro.setEnabled(true);
            try {
                jcbBairro.setModel(carregaEndereco.carregaBairro((Cidade) jcbCidade.getSelectedItem()));
            } catch (Exception e) {
                jcbBairro.getModel().setSelectedItem(new Bairro(0, 0, "-Selecione-", "-Selecione-"));
            }
        }
    }//GEN-LAST:event_jcbCidadeItemStateChanged

    private void jcbLogradouroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLogradouroItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            jcbCEP_ZIP.setEnabled(true);
            jcbCEP_ZIP.setModel(carregaEndereco.carregaCEP_ZIP((Bairro) jcbBairro.getSelectedItem()));
        }
    }//GEN-LAST:event_jcbLogradouroItemStateChanged

    private void jcbCEP_ZIPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCEP_ZIPItemStateChanged
    }//GEN-LAST:event_jcbCEP_ZIPItemStateChanged

    private void jcbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEstadoItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            jcbCidade.setEnabled(true);
            jcbCidade.setModel(carregaEndereco.carregaCidade((Estado) jcbEstado.getSelectedItem()));
        }
    }//GEN-LAST:event_jcbEstadoItemStateChanged

    private void jcbBairroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBairroItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED) {
            jcbLogradouro.setEnabled(true);
            jcbLogradouro.setModel(carregaEndereco.carregaEndereco((Bairro) jcbBairro.getSelectedItem()));
        }
    }//GEN-LAST:event_jcbBairroItemStateChanged

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        if (jtfNome.getText().contains("1")
                || jtfNome.getText().contains("2")
                || jtfNome.getText().contains("3")
                || jtfNome.getText().contains("4")
                || jtfNome.getText().contains("5")
                || jtfNome.getText().contains("6")
                || jtfNome.getText().contains("7")
                || jtfNome.getText().contains("8")
                || jtfNome.getText().contains("9")
                || jtfNome.getText().contains("0")) {

            String tamanho = jtfNome.getText();
            int posicao = 0;

            while (posicao < tamanho.length() - 1) {
                char verificado = tamanho.charAt(posicao);
                Character vazio = (null);
                if (Character.isDigit(verificado)) {
                    jtfNome.setText(jtfNome.getText().replace(verificado, vazio));
                }
            }
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {
        acaoGravar();
    }

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        if (p.getNome() != null) {
            controladorPessoa = new ControladorPessoa();
            controladorPessoa.removePessoa(p);
        } else {
            m = new Mensagens();
            m.jopAlerta("É necessário buscar um cadastro antes de excluir.");
        }
    }

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {
        acaoBuscar();
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPessoal dialog = new CadastroPessoal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbBairro;
    private javax.swing.JComboBox jcbCEP_ZIP;
    private javax.swing.JComboBox jcbCidade;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JComboBox jcbLogradouro;
    private javax.swing.JComboBox jcbPais;
    private javax.swing.JFormattedTextField jftfDataNascimento;
    private javax.swing.JFormattedTextField jftfNome;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCEP_ZIP;
    private javax.swing.JLabel jlCPF_CNPJ;
    private javax.swing.JLabel jlCadastro;
    private javax.swing.JLabel jlCadastroNmr;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlDataNascimento;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlLogradouro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlPais;
    private javax.swing.JLabel jlRG;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JPanel jpAgrupador;
    private javax.swing.JPanel jpCadastro;
    private javax.swing.JPanel jpControles;
    private javax.swing.JPanel jpDadosFuncionario;
    private javax.swing.JPanel jpDadosPessoais;
    private javax.swing.JPanel jpDadosPrincipais;
    private javax.swing.JPanel jpEndereco;
    private javax.swing.JPanel jpLabelsDP;
    private javax.swing.JPanel jpLabelsE;
    private javax.swing.JPanel jpLablesDPessoais;
    private javax.swing.JPanel jpPessoal;
    private javax.swing.JPanel jpTextFieldsDP;
    private javax.swing.JPanel jpTextFieldsDPessoais;
    private javax.swing.JPanel jpTextFieldsE;
    private javax.swing.JScrollPane jspPainelRolagem;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfCPF_CNPJ;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfDDD;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTabbedPane jtpAbas;
    // End of variables declaration//GEN-END:variables

    public boolean validaCampos() {

        if (jtfNome.getText().equals("")) {
            m = new Mensagens();
            m.jopAlerta("Por favor preencha o campo 'Nome'.");
            return false;

        } else {


            this.p.setNome(jtfNome.getText());

            if (jtfRG.getText().equals("")) {
                m = new Mensagens();
                m.jopAlerta("Por favor preencha o campo 'RG'.");
                return false;

            } else {
                if (VerificaNumeros.verificaNumeros(jtfRG.getText())) {
                    this.p.setRG(Integer.parseInt(jtfRG.getText()));
                } else {
                    Mensagens m = new Mensagens();
                    m.jopAlerta("Informe apenas números no campo 'RG'.");
                }
                if (jtfCPF_CNPJ.getText().equals("")) {
                    m = new Mensagens();
                    m.jopAlerta("Por favor preencha o campo 'CPF/CNPJ'.");
                    return false;

                } else {
                    if (VerificaNumeros.verificaNumeros(jtfCPF_CNPJ.getText())) {
                        this.p.setCPF_CNPJ(Integer.parseInt(jtfCPF_CNPJ.getText()));
                    } else {
                        Mensagens m = new Mensagens();
                        m.jopAlerta("Informe apenas números no campo 'CPF/CNPJ'.");
                    }
                    if (!jcbCidade.isEnabled()) {
                        return false;

                    } else if (!jcbBairro.isEnabled()) {
                        return false;

                    } else {
                        Pais pais = new Pais();
                        Estado estado = new Estado();
                        Cidade cidade = new Cidade();
                        Bairro bairro = new Bairro();

                        pais = (Pais) jcbPais.getSelectedItem();
                        estado = (Estado) jcbEstado.getSelectedItem();
                        cidade = (Cidade) jcbCidade.getSelectedItem();
                        bairro = (Bairro) jcbBairro.getSelectedItem();

                        if (!jcbLogradouro.isEnabled()) {
                            return false;

                        } else {
                            Endereco endereco = new Endereco();
                            endereco = (Endereco) jcbLogradouro.getSelectedItem();

                            if (jtfNumero.getText().equals("")) {
                                m = new Mensagens();
                                m.jopAlerta("Por favor preencha o campo 'Número'.");
                                return false;

                            } else {
                                if (VerificaNumeros.verificaNumeros(jtfNumero.getText())) {
                                    this.p.setNumero(Integer.parseInt(jtfNumero.getText()));
                                } else {
                                    Mensagens m = new Mensagens();
                                    m.jopAlerta("Informe apenas números no campo 'Número'.");
                                }

                                if (!jcbCEP_ZIP.isEnabled()) {
                                    return false;

                                } else {

                                    CEP_ZIP cep_zip = new CEP_ZIP();

                                    cep_zip = (CEP_ZIP) jcbCEP_ZIP.getSelectedItem();

                                    if (jtfComplemento.getText().equals("")) {
                                        m = new Mensagens();
                                        m.jopAlerta("Por favor preencha o campo 'Complemento'.");
                                        return false;
                                    } else {
                                        this.p.setComplemento(jtfComplemento.getText());
                                        this.p.setIdPais(pais.getCodigo());
                                        this.p.setIdEstado(estado.getId());
                                        this.p.setIdCidade(cidade.getCodigo());
                                        this.p.setIdBairro(bairro.getIdBairro());
                                        this.p.setIdLogradouro(endereco.getIdBairro());
                                        this.p.setCEP_ZIP(cep_zip.getCep_zip());

//comentado pois a gravação do telefone está falha. Sendo assim não será feita validação dos campos.

//                                        if (jtfTelefone.getText().equals("")) {
//                                            m = new Mensagens();
//                                            m.jopAlerta("Por favor preencha o campo 'Telefone'.");
//                                            return false;
//                                        } else {

//                                            if (VerificaNumeros.verificaNumeros(jtfTelefone.getText())) {
//                                                t.setNumero(Integer.parseInt(jtfTelefone.getText()));
//                                                if (VerificaNumeros.verificaNumeros(jtfDDD.getText())) {
//                                                    t.setDDD(Integer.parseInt(jtfDDD.getText()));
//                                                }
//                                            }else {
//                                                Mensagens m = new Mensagens();
//                                                m.jopAlerta("Informe apenas números no campo 'Telefone'.");
//                                            }
                                        if (jftfDataNascimento.getText().equals("")) {
                                            m = new Mensagens();
                                            m.jopAlerta("Por favor preencha o campo 'Data de Nascimento'.");
                                            return false;
                                        } else {
                                            try {
                                                this.p.setNascimento(new SimpleDateFormat("dd/MM/yyyy").parse(jftfDataNascimento.getText()));
                                            } catch (ParseException ex) {
                                                Logger.getLogger(CadastroPessoal.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }

                                        return true;
//                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void acaoBuscar() {
        if (!jtfBuscar.getText().equals("")) {
            controladorPessoa = new ControladorPessoa();
            p.setIdPessoa(Integer.parseInt(jtfBuscar.getText()));
            p = controladorPessoa.buscaPessoa(p);

            jtfNome.setText(p.getNome());
            jtfCPF_CNPJ.setText(p.getCPF_CNPJ() + "");
            jtfRG.setText(p.getRG() + "");
            jtfNumero.setText(p.getNumero() + "");
            jtfComplemento.setText(p.getComplemento());
            jftfDataNascimento.setText(p.getNascimento().toString());

            Pais pais = new Pais("", "", p.getIdPais());
            Estado estado = new Estado("", "", 0, p.getIdEstado());
            Cidade cidade = new Cidade("", 0, p.getIdCidade());
            Bairro bairro = new Bairro(p.getIdBairro(), 0, "", "");
            Bairro bairroCEP = new Bairro(p.getIdBairro(), 0, "", "");
            Endereco endereco = new Endereco(0, p.getIdBairro(), "", 0, 0, "");

            jcbPais.removeAll();
            jcbEstado.removeAll();
            jcbCidade.removeAll();
            jcbBairro.removeAll();
            jcbLogradouro.removeAll();
            jcbCEP_ZIP.removeAll();

            jcbPais.setModel(carregaEndereco.carregaPais());
            jcbEstado.setModel(carregaEndereco.carregaEstado((Pais) jcbPais.getSelectedItem()));
            jcbCidade.setModel(carregaEndereco.carregaCidade(estado));
            jcbBairro.setModel(carregaEndereco.carregaBairro(cidade));
            jcbLogradouro.setModel(carregaEndereco.carregaEndereco(bairro));
            jcbCEP_ZIP.setModel(carregaEndereco.carregaCEP_ZIP(bairroCEP));

            pais.setCodigo(p.getIdPais());

            jcbPais.setSelectedItem(pais);
            jcbEstado.setSelectedItem(estado);
            jcbCidade.setSelectedItem(cidade);
            jcbBairro.setSelectedItem(bairro);
            jcbCEP_ZIP.setSelectedItem(bairroCEP);
            jcbLogradouro.setSelectedItem(endereco);

            jcbCidade.setEnabled(true);
            jcbBairro.setEnabled(true);
            jcbLogradouro.setEnabled(true);
            jcbCEP_ZIP.setEnabled(true);

            jcbPais.updateUI();
            jcbEstado.updateUI();
            jcbCidade.updateUI();
            jcbBairro.updateUI();
            jcbLogradouro.updateUI();
            jcbCEP_ZIP.updateUI();

        } else {
            m = new Mensagens();
            m.jopAlerta("É necessário informar o código de um cadastro antes de pesquisar.");
        }
    }

    public void acaoGravar() {
        if (validaCampos()) {
            controladorPessoa = new ControladorPessoa();

            boolean inserePessoa = controladorPessoa.inserePessoa(p, t);

            if (inserePessoa) {
                Mensagens m = new Mensagens();
                m.jopAviso("Cadastro realizado com sucesso!");
            }

            jtfBuscar.setText("");
            jtfNome.setText("");
            jtfRG.setText("");
            jtfCPF_CNPJ.setText("");
            jtfNumero.setText("");
            jtfComplemento.setText("");
            jtfDDD.setText("");
            jtfTelefone.setText("");
            jftfDataNascimento.setText("");

            jcbPais.setSelectedIndex(0);
            jcbEstado.setSelectedIndex(0);
            jcbCidade.setSelectedIndex(0);
            jcbBairro.setSelectedIndex(0);
            jcbLogradouro.setSelectedIndex(0);
            jcbCEP_ZIP.setSelectedIndex(0);

            jcbCidade.setEnabled(false);
            jcbBairro.setEnabled(false);
            jcbLogradouro.setEnabled(false);
            jcbCEP_ZIP.setEnabled(false);
        }
    }

    public void acaoAlterar() {
        if (validaCampos()) {
        }

    }
}
