/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class TCC extends javax.swing.JFrame {

    /**
     * Creates new form TCC
     */
    public TCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiFabricante = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jmiCaixa = new javax.swing.JMenuItem();
        jmiCadastroUsuario = new javax.swing.JMenuItem();
        jmFinanceiro = new javax.swing.JMenu();
        jmiBaixaDeTituloPagar = new javax.swing.JMenuItem();
        jmVenda = new javax.swing.JMenu();
        jmiVenda = new javax.swing.JMenuItem();
        jmiAbrirCaixa = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TCC - Bruno");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("TCC - Bruno"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jmCadastro.setText("Cadastro");

        jmiFabricante.setText("jMenuItem1");
        jmCadastro.add(jmiFabricante);

        jmiFornecedor.setText("jMenuItem1");
        jmCadastro.add(jmiFornecedor);

        jmiProduto.setText("jMenuItem1");
        jmCadastro.add(jmiProduto);

        jmiCaixa.setText("jMenuItem1");
        jmCadastro.add(jmiCaixa);

        jmiCadastroUsuario.setText("jMenuItem1");
        jmCadastro.add(jmiCadastroUsuario);

        jMenuBar1.add(jmCadastro);

        jmFinanceiro.setText("Financeiro");

        jmiBaixaDeTituloPagar.setText("jMenuItem1");
        jmFinanceiro.add(jmiBaixaDeTituloPagar);

        jMenuBar1.add(jmFinanceiro);

        jmVenda.setText("Venda");

        jmiVenda.setText("jMenuItem1");
        jmVenda.add(jmiVenda);

        jmiAbrirCaixa.setText("jMenuItem1");
        jmVenda.add(jmiAbrirCaixa);

        jMenuBar1.add(jmVenda);

        jmRelatorios.setText("Relatórios");
        jMenuBar1.add(jmRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-339)/2, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(null,"flowwww");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCC().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmFinanceiro;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenu jmVenda;
    private javax.swing.JMenuItem jmiAbrirCaixa;
    private javax.swing.JMenuItem jmiBaixaDeTituloPagar;
    private javax.swing.JMenuItem jmiCadastroUsuario;
    private javax.swing.JMenuItem jmiCaixa;
    private javax.swing.JMenuItem jmiFabricante;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiVenda;
    // End of variables declaration//GEN-END:variables
}
