/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controlador.Sessao;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author Bruno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        jmCadastro.setVerticalTextPosition(SwingConstants.BOTTOM);
        jmCadastro.setHorizontalTextPosition(SwingConstants.CENTER);

        jmConfiguracoes.setVerticalTextPosition(SwingConstants.BOTTOM);
        jmConfiguracoes.setHorizontalTextPosition(SwingConstants.CENTER);

        jmProcessos.setVerticalTextPosition(SwingConstants.BOTTOM);
        jmProcessos.setHorizontalTextPosition(SwingConstants.CENTER);

        if (null != Sessao.getInstance().getUsuario().getNome() && !("".equals(Sessao.getInstance().getUsuario().getNome()))) {
            jlNomeUsuario.setText(Sessao.getInstance().getUsuario().getNome());
        } else {
            jlNomeUsuario.setText("-");
        }
        
        if (null != Sessao.getInstance().getUsuario().getNome() && !("".equals(Sessao.getInstance().getUsuario().getNome()))) {
            jlPerfil.setText(Sessao.getInstance().getUsuario().getPerfil()+"");
        } else {
            jlPerfil.setText("-");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlNomeUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlPerfil = new javax.swing.JLabel();
        jmbBarraMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiPessoas = new javax.swing.JMenuItem();
        jmiImovel = new javax.swing.JMenuItem();
        jmComplementares = new javax.swing.JMenu();
        jmiEmbutidos = new javax.swing.JMenuItem();
        jmProcessos = new javax.swing.JMenu();
        jmiVenda = new javax.swing.JMenuItem();
        jmConfiguracoes = new javax.swing.JMenu();
        jmiConexao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Imob");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlNomeUsuario.setText("(NomeUsuario)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlNomeUsuario)
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNomeUsuario)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlPerfil.setText("(Perfil)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlPerfil)
                .addGap(0, 449, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlPerfil))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jmCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/Cadastro_64x64.png"))); // NOI18N
        jmCadastro.setText("Cadastro");

        jmiPessoas.setText("Pessoas");
        jmiPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPessoasActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiPessoas);

        jmiImovel.setText("Imóvel");
        jmiImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImovelActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiImovel);

        jmComplementares.setText("Complementares");

        jmiEmbutidos.setText("Embutidos(Descontinuado)");
        jmiEmbutidos.setEnabled(false);
        jmiEmbutidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmbutidosActionPerformed(evt);
            }
        });
        jmComplementares.add(jmiEmbutidos);

        jmCadastro.add(jmComplementares);

        jmbBarraMenu.add(jmCadastro);

        jmProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/Processos_64x64.png"))); // NOI18N
        jmProcessos.setText("Processos");

        jmiVenda.setText("Venda");
        jmiVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendaActionPerformed(evt);
            }
        });
        jmProcessos.add(jmiVenda);

        jmbBarraMenu.add(jmProcessos);

        jmConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/Cofigure_64x64.png"))); // NOI18N
        jmConfiguracoes.setText("Configurações");

        jmiConexao.setText("Conexão");
        jmiConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConexaoActionPerformed(evt);
            }
        });
        jmConfiguracoes.add(jmiConexao);

        jmbBarraMenu.add(jmConfiguracoes);

        setJMenuBar(jmbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 212, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-720)/2, (screenSize.height-338)/2, 720, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImovelActionPerformed
        CadastroImovelN cI = new CadastroImovelN();
        cI.setVisible(true);
    }//GEN-LAST:event_jmiImovelActionPerformed

    private void jmiEmbutidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmbutidosActionPerformed
    }//GEN-LAST:event_jmiEmbutidosActionPerformed

    private void jmiConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConexaoActionPerformed
        dConexaoTela c = new dConexaoTela(this, rootPaneCheckingEnabled);
        c.setVisible(true);
    }//GEN-LAST:event_jmiConexaoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jmiPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPessoasActionPerformed
        CadastroPessoaN cP = new CadastroPessoaN(this, rootPaneCheckingEnabled);
        cP.setVisible(true);    }//GEN-LAST:event_jmiPessoasActionPerformed

    private void jmiVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendaActionPerformed
        VendaImovelN venda = new VendaImovelN(this, rootPaneCheckingEnabled);
        venda.setVisible(true);
    }//GEN-LAST:event_jmiVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlPerfil;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmComplementares;
    private javax.swing.JMenu jmConfiguracoes;
    private javax.swing.JMenu jmProcessos;
    private javax.swing.JMenuBar jmbBarraMenu;
    private javax.swing.JMenuItem jmiConexao;
    private javax.swing.JMenuItem jmiEmbutidos;
    private javax.swing.JMenuItem jmiImovel;
    private javax.swing.JMenuItem jmiPessoas;
    private javax.swing.JMenuItem jmiVenda;
    // End of variables declaration//GEN-END:variables
}
