/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Cadastro.Administrativo;

import Componentes.Componentes;
//import ConstrutoresModelo.ConstrutorFuncionario;
import controller.Cadastro.Administrativo.FuncionarioController;
import controller.Mensagens;
import controller.PerfilController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
//import modelo.Funcionario;

//import modelo.Perfil;

/**
 *
 * @author Bruno
 */
public class CadastroFuncionario extends javax.swing.JDialog {

    Componentes c = new Componentes();
    JButton jbGravar  = c.criaBotaoGravar();
    JButton jbBuscar  = c.criaBotaoBuscar();
    JButton jbExcluir = c.criaBotaoExcluir();
//    Funcionario f;
    FuncionarioController fController;
    PerfilController pController;
    Mensagens m;
//    ConstrutorFuncionario cF;
//    DefaultComboBoxModel<Perfil> modeloPerfil;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jpBotoes.add(jbGravar);
        jpBotoes.add(jbBuscar);
        jpBotoes.add(jbExcluir);

//        carregaListaPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDadosBasicos = new javax.swing.JPanel();
        jpTextField = new javax.swing.JPanel();
        jcbNome = new javax.swing.JComboBox();
        jtfTelefone = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jtfRG = new javax.swing.JTextField();
        jtfCTPS = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jpLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpDadosUsuario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcbPerfil = new javax.swing.JComboBox();
        jchckbAtivo = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jtfUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpEndLbl = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jpEndTxt = new javax.swing.JPanel();
        jtfRua = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfCEP = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jtfPais = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jpBotoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de usuários");
        setResizable(false);

        jpDadosBasicos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jpTextField.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        jpTextField.add(jcbNome);
        jpTextField.add(jtfTelefone);
        jpTextField.add(jtfCPF);
        jpTextField.add(jtfRG);
        jpTextField.add(jtfCTPS);
        jpTextField.add(jtfEmail);

        jpLabel.setLayout(new java.awt.GridLayout(6, 1, 0, 11));

        jLabel1.setText("Nome:");
        jpLabel.add(jLabel1);

        jLabel2.setText("Telefone:");
        jpLabel.add(jLabel2);

        jLabel3.setText("CPF:");
        jpLabel.add(jLabel3);

        jLabel4.setText("RG:");
        jpLabel.add(jLabel4);

        jLabel5.setText("CTPS:");
        jpLabel.add(jLabel5);

        jLabel6.setText("E-mail:");
        jpLabel.add(jLabel6);

        javax.swing.GroupLayout jpDadosBasicosLayout = new javax.swing.GroupLayout(jpDadosBasicos);
        jpDadosBasicos.setLayout(jpDadosBasicosLayout);
        jpDadosBasicosLayout.setHorizontalGroup(
            jpDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpDadosBasicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpDadosBasicosLayout.setVerticalGroup(
            jpDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
            .addGroup(jpDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpDadosBasicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Perfil:");

        jchckbAtivo.setText("Ativo");

        jLabel15.setText("Usuário:");

        jpfSenha.setText("jPasswordField1");

        jLabel16.setText("Senha:");

        javax.swing.GroupLayout jpDadosUsuarioLayout = new javax.swing.GroupLayout(jpDadosUsuario);
        jpDadosUsuario.setLayout(jpDadosUsuarioLayout);
        jpDadosUsuarioLayout.setHorizontalGroup(
            jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpDadosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jchckbAtivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosUsuarioLayout.setVerticalGroup(
            jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchckbAtivo))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jpEndLbl.setLayout(new java.awt.GridLayout(7, 1));

        jLabel8.setText("Rua:");
        jpEndLbl.add(jLabel8);

        jLabel9.setText("Número:");
        jpEndLbl.add(jLabel9);

        jLabel10.setText("CEP:");
        jpEndLbl.add(jLabel10);

        jLabel14.setText("Bairro");
        jpEndLbl.add(jLabel14);

        jLabel11.setText("Cidade:");
        jpEndLbl.add(jLabel11);

        jLabel12.setText("Estado:");
        jpEndLbl.add(jLabel12);

        jLabel13.setText("País:");
        jpEndLbl.add(jLabel13);

        jpEndTxt.setLayout(new java.awt.GridLayout(7, 1, 0, 4));
        jpEndTxt.add(jtfRua);
        jpEndTxt.add(jtfNumero);
        jpEndTxt.add(jtfCEP);
        jpEndTxt.add(jtfCidade);
        jpEndTxt.add(jtfEstado);
        jpEndTxt.add(jtfPais);
        jpEndTxt.add(jtfBairro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jpEndLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpEndTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpEndLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEndTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBotoes.setLayout(new java.awt.GridLayout(1, 4, 0, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosBasicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDadosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jpDadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {
//        acaoGravar();
    }

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {
//        m = new Mensagens();
//        if (m.jopDeletar("Deseja realmente excluir este fucionário ?") == JOptionPane.YES_OPTION) {
//            acaoRemover();
//        }
    }

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {
//        acaoBuscar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroFuncionario dialog = new CadastroFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbNome;
    private javax.swing.JComboBox jcbPerfil;
    private javax.swing.JCheckBox jchckbAtivo;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpDadosBasicos;
    private javax.swing.JPanel jpDadosUsuario;
    private javax.swing.JPanel jpEndLbl;
    private javax.swing.JPanel jpEndTxt;
    private javax.swing.JPanel jpLabel;
    private javax.swing.JPanel jpTextField;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCEP;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfCTPS;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfPais;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

    public boolean validaCampos() {
        if (((null != jcbNome.getSelectedItem())
                && (null != jcbNome.getSelectedItem())
                && ((null != jtfBairro.getText()) && !("".equals(jtfBairro.getText())))
                && ((null != jtfCidade.getText()) && !("".equals(jtfCidade.getText())))
                && ((null != jtfRua.getText()) && !("".equals(jtfRua.getText())))
                && ((null != jtfPais.getText()) && !("".equals(jtfPais.getText())))
                && ((null != jtfTelefone.getText()) && !("".equals(jtfTelefone.getText())))
                && ((null != jtfCTPS.getText()) && !("".equals(jtfCTPS.getText())))
                && ((null != jtfRG.getText()) && !("".equals(jtfRG.getText())))
                && ((null != jtfCPF.getText()) && !("".equals(jtfCPF.getText())))
                && ((null != jtfEmail.getText()) && !("".equals(jtfEmail.getText()))))) {

//            cF = new ConstrutorFuncionario();
//            f = cF.nome(jcbNome.getSelectedItem().toString())
//                    .email(jtfEmail.getText())
//                    .nomeUsuario(jtfUsuario.getText())
//                    .senha(new String(jpfSenha.getPassword()))
//                    .telefone(jtfTelefone.getText())
//                    .CTPS(jtfCTPS.getText())
//                    .CPF(Integer.parseInt(jtfCPF.getText()))
//                    .RG(Integer.parseInt(jtfRG.getText()))
//                    .idFuncionario(0)
//                    .idUsuario(0)
//                    .construir();

//            if (jchckbAtivo.isSelected()) {
//                f.setAtivo(1);
//            } else {
//                f.setAtivo(0);
//            }

            return true;
        } else {
            return false;
        }
    }

//    public void acaoGravar() {
//        if (validaCampos()) {
//             fController.gravar(f); 
////                m = new Mensagens();
////                m.jopAviso("Cadastro realizado com sucesso!");
////            }
//            limparTela();
//        } else {
//            m = new Mensagens();
//            m.jopAviso("Exitem campos vazios, preencha todos os campos antes de gravar.");
//        }
//    }

//    public void acaoAlterar() {
//        if (validaCampos()) {
//            fController.alterar(f);
//        }
//    }

//    public void acaoBuscar() {
//        if (null != jcbNome.getSelectedItem().toString() && !("".equals(jcbNome.getSelectedItem().toString()))) {
//            if (!jtfCPF.getText().equals("")) {
//
//                DefaultComboBoxModel dcbm = fController.buscar("cpf", jtfCPF.getText());
//
//                if (dcbm != null) {
//
//                    jcbNome.setModel(dcbm);
//                    if (jcbNome.getItemCount() >= 1) {
//                        jcbNome.setSelectedIndex(-1);
//                        jcbNome.setSelectedIndex(0);
//                    } else {
//                        m = new Mensagens();
//                        m.jopAviso("Nenhum funcionário encontrado.");
//                       // return false;
//                    }
//                    //return true;
//                } else {
//                    m = new Mensagens();
//                    m.jopAviso("Nenhum funcionário encontrado.");
//                    //return false;
//                }
//            } else {
//                m = new Mensagens();
//                m.jopAviso("É nescessário informar o nome da pessoa para efetuar uma busca.");
//                //return false;
//            }
//        }
//    }

//    public void acaoRemover() {
//        if (acaoBuscar()) {
//            cF = new FuncionarioDAO();
//            imovel = (ImovelN) jcbNumero.getSelectedItem();
//            controladorImovel.removeImovel(imovel);
//        }
//        limparTela();
//    }
    public void limparTela() {
        jcbNome.setSelectedIndex(-1);
        jcbPerfil.setSelectedIndex(-1);
        jtfBairro.setText("");
        jtfCEP.setText("");
        jtfCPF.setText("");
        jtfCTPS.setText("");
        jtfCidade.setText("");
        jtfEmail.setText("");
        jtfEstado.setText("");
        jtfNumero.setText("");
        jtfPais.setText("");
        jtfRG.setText("");
        jtfRua.setText("");
        jtfTelefone.setText("");
        jtfUsuario.setText("");
        jpfSenha.setText("");
        jchckbAtivo.setSelected(false);
    }

//    private void carregaListaPerfil() {
//        modeloPerfil = new DefaultComboBoxModel<>();
//        modeloPerfil = pController.listaPerfil();
//        jcbPerfil.setModel(modeloPerfil);
//    }
}
