/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.Cadastro.Administrativo.Permissoes;

import Componentes.Componentes;
import controller.Mensagens;
import controller.ModuloController;
//import controller.ModuloController;
import controller.PerfilController;
import javax.swing.JButton;
import javax.swing.JPanel;
import modelo.PerfisPermissoes.Modulo;
import modelo.PerfisPermissoes.ModuloPermissao;
import modelo.PerfisPermissoes.Perfil;
import modelo.PerfisPermissoes.PerfilModulopermissao;
import modelo.PerfisPermissoes.Permissao;

/**
 *
 * @author Bruno
 */
public class CadastroPermissoes extends javax.swing.JDialog {

    Perfil perfil = new Perfil();
    Modulo modulo = new Modulo();
    ModuloPermissao modulopermissao = new ModuloPermissao();
    PerfilModulopermissao perfilModulopermissao = new PerfilModulopermissao();
    Permissao permissao = new Permissao();
    Componentes c = new Componentes();
    ModuloController moduloController = new ModuloController();
    PerfilController pcerfilController = new PerfilController();
    JButton jbGravar;
    JButton jbExcluir;
    private Mensagens m;

    /**
     * Creates new form CadastroPermissoes
     */
    public CadastroPermissoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jbGravar = c.criaBotaoGravar();
        jbExcluir = c.criaBotaoExcluir();

        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jpControles.add(jbExcluir);
        jpControles.add(jbGravar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbModulo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jchkbGravar = new javax.swing.JCheckBox();
        jchkbAlterar = new javax.swing.JCheckBox();
        jchkbExcluir = new javax.swing.JCheckBox();
        jchckConsultar = new javax.swing.JCheckBox();
        jbGravarPermissao = new javax.swing.JButton();
        jtfPerfil = new javax.swing.JTextField();
        jpControles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil"));
        jPanel1.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seção"));

        jLabel1.setText("Módulo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbModulo, 0, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissão"));

        jchkbGravar.setText("Gravar");

        jchkbAlterar.setText("Alterar");

        jchkbExcluir.setText("Excluir");

        jchckConsultar.setText("Consultar");

        jbGravarPermissao.setText("Gravar");
        jbGravarPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarPermissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkbGravar)
                    .addComponent(jchkbAlterar))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchckConsultar)
                    .addComponent(jchkbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGravarPermissao)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGravarPermissao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchkbGravar)
                            .addComponent(jchkbExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchkbAlterar)
                            .addComponent(jchckConsultar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfPerfil)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jpControles.setLayout(new java.awt.GridLayout(1, 3, 3, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jbGravarPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarPermissaoActionPerformed
//        vinculaPermissaoModulo();
    }//GEN-LAST:event_jbGravarPermissaoActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {
//        acaoGravar();
    }

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {
//        m = new Mensagens();
//        if (m.jopDeletar("Deseja realmente excluir este fucionário ?") == JOptionPane.YES_OPTION) {
//            acaoRemover();
//        }
    }

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {
//        acaoBuscar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPermissoes dialog = new CadastroPermissoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setSize(400, 320);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbGravarPermissao;
    private javax.swing.JComboBox jcbModulo;
    private javax.swing.JCheckBox jchckConsultar;
    private javax.swing.JCheckBox jchkbAlterar;
    private javax.swing.JCheckBox jchkbExcluir;
    private javax.swing.JCheckBox jchkbGravar;
    private javax.swing.JPanel jpControles;
    private javax.swing.JTextField jtfPerfil;
    // End of variables declaration//GEN-END:variables

    public void carregaTela() {
        jbGravar = c.criaBotaoGravar();
//        jbBuscar = c.criaBotaoBuscar();
        jbExcluir = c.criaBotaoExcluir();
        jpControles = new JPanel();
//        jpControles.add(jbBuscar);
        jpControles.add(jbExcluir);
        jpControles.add(jbGravar);
    }

//    public Permissao configuraCheckBoxPermissao() {
//        if (!jchkbAlterar.isSelected()
//                && !jchkbExcluir.isSelected()
//                && !jchkbGravar.isSelected()
//                && !jchckConsultar.isSelected()) {
//            Permissao permissao;
//            m = new Mensagens();
//            int resposta = JOptionPane.showConfirmDialog(null, "A configuração efetuada resultará "
//                    + "em um perfil sem permissões para o módulo "
//                    + "escolhido.",
//                    "Cuidado",
//                    JOptionPane.YES_NO_OPTION);
//            if (resposta == JOptionPane.NO_OPTION) {
//                permissao = new Permissao();
//                if (jchkbAlterar.isSelected()) {
//                    permissao.setPermissaoAlterar();
//                }
//                if (jchkbExcluir.isSelected()) {
//                    permissao.setPermissaoExcluir();
//                }
//                if (jchkbGravar.isSelected()) {
//                    permissao.setPermissaoGravar();
//                }
//                if (jchckConsultar.isSelected()) {
//                    permissao.setPermissaoVisualizar();
//                }
//            }
//        }
//        return permissao;
//    }

//    public void acaoGravar() {
//        if (perfilController.gravar(perfil)) {
//            m.jopAviso("Perfil gravado com sucesso!");
//            limparTela();
//        }
//    }

    public void limparTela() {
        jcbModulo.setSelectedIndex(-1);
        jtfPerfil.setText("");
        jchckConsultar.setSelected(false);
        jchkbAlterar.setSelected(false);
        jchkbExcluir.setSelected(false);
        jchkbGravar.setSelected(false);
    }

//    private void vinculaPermissaoModulo() {
//        Modulo modulo;
//        Permissao permissao;
//
//        modulo = (Modulo) jcbModulo.getSelectedItem();
//        permissao = configuraCheckBoxPermissao();
//
//        adicionaListaPermissoesModulos(modulo, permissao);
//
//    }
//
//    public void adicionaListaPermissoesModulos(Modulo modulo, Permissao permissao) {
//        modulopermissao = new Modulopermissao();
//        modulopermissao.setModulo(modulo);
//        modulopermissao.setPermissao(permissao);
//        perfilModulopermissao.setModulopermissao(modulopermissao);
//        perfilModulopermissaoList.add(perfilModulopermissao);
//        perfil.getPerfilModulopermissaoList().add(perfilModulopermissao);
//    }

//    private void carregaPerfis() {
//        DefaultComboBoxModel<Perfil> dcbm;
//        dcbm = perfilController.listaPerfil();
//        jcbPerfil.setModel(dcbm);
//    }
//    
//    private void carregaModulos() {
//        DefaultComboBoxModel<Modulo> dcbm;
////        dcbm = moduloController.listaModulo();
//        jcbPerfil.setModel(dcbm);
//    }
}
